# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dTtNJyItlAS9xSAqbRP2BRvYl39RgS6g
"""

import re
import sympy as sp

# Inicializa os símbolos do SymPy para as variáveis principais
x, y, z, n = sp.symbols("x y z n")

print("=== CALCULADORA UNIVERSAL COMPLETA (MODO ENGENHARIA) ===")
print("Operações aceitas:")
print(" - Regra de 3 Simples: 'r3 3 15 8' ou 'regra3 3 15 8'")
print(" - Lei de formação direta: 'an = n5 + 15' ou 'an = 2n + 3'")
print(" - Descobrir lei por termos: 'seq 16, 17, 18, 19, 20' ou 'sequencia 2, 4, 6, 8'")
print(" - MMC e MDC rápidos: 'mmc 40, 12' ou 'mdc 24 36'")
print(" - Divisão Normal: '50/4' (Resultado: 12,5)")
print(" - Frações com barra vertical: '12|15 + 7|8' (Resultado em Fração: 67|40)")
print(" - Números Decimais com Vírgula: '1,5 + 1,15' ou 'raiz de 2,25'")
print(" - Equações completas: '2x = 18' ou 'x + 5 = 20'")
print(" - Multiplicação implícita: '2x', '5n', '3(x+1)'")
print(" - Ponto como Multiplicação: '2.3' vira 2*3 (Resultado: 6)")
print(" - Raiz Quadrada: 'raiz de 13', 'raiz 16', '√16' ou 'raiz(16)'")
print(" - Regra dos 180° (Ângulos): 'angulo 60 50'")
print("Digite 'sair' para fechar.\n" + "-" * 40)

def tratar_virgula(match):
    inteiro = match.group(1)
    decimal = match.group(2)
    return f"({inteiro}{decimal}/{10**len(decimal)})"

while True:
    entrada = input(">>> ").strip().lower()

    if entrada == "sair":
        break
    if not entrada:
        continue

    try:
        # 1. ATALHO: Regra de Três Simples (ex: "r3 3 15 8" -> 3/15 = 8/x)
        if entrada.startswith(("regra3", "regra de 3", "r3")):
            # Remove o comando inicial para o '3' de 'r3' não ser lido como número
            texto_limpo = re.sub(r"^(regra\s*de\s*3|regra3|r3)", "", entrada).strip()
            numeros = re.findall(r"-?\d+(?:[\.,]\d+)?", texto_limpo)

            if len(numeros) == 3:
                a, b, c = [float(n.replace(",", ".")) for n in numeros]
                if a != 0:
                    x_res = (b * c) / a
                    x_str = str(int(x_res) if x_res.is_integer() else round(x_res, 4)).replace(".", ",")
                    print(f"Resultado da Regra de Três: x = {x_str}\n")
                else:
                    print("Erro: O primeiro valor não pode ser zero!\n")
                continue
            else:
                print("Erro: Digite 3 valores (ex: 'r3 3 15 8')!\n")
                continue

        # 2. ATALHO: Descobrir Lei de Formação a partir de uma Sequência
        if entrada.startswith(("seq ", "sequencia ", "sequência ")):
            numeros = re.findall(r"-?\d+(?:,\d+)?", entrada.replace("seq", "").replace("uência", "").replace("uencia", ""))

            if len(numeros) >= 2:
                valores = [sp.sympify(num.replace(",", ".")) for num in numeros]
                pontos = {i + 1: val for i, val in enumerate(valores)}

                lei_encontrada = sp.interpolate(pontos, n)
                lei_simplificada = sp.simplify(lei_encontrada)

                print(f"Lei de formação encontrada: A_n = {lei_simplificada}")
                print(f"Termos informados: {valores}\n")
                continue
            else:
                print("Erro: Informe pelo menos 2 termos para encontrar a lei de formação!\n")
                continue

        # 3. ATALHO: Aplicação da Lei de Formação Informada
        if re.match(r"^a_?n\s*=", entrada):
            expressao_lei = entrada.split("=")[1].strip()

            expressao_lei = re.sub(r"n(\d+)", r"n*\1", expressao_lei)
            expressao_lei = re.sub(r"(\d+)n", r"\1*n", expressao_lei)
            expressao_lei = expressao_lei.replace("^", "**")

            expr_seq = sp.sympify(expressao_lei, locals={"n": n})

            termos = [expr_seq.subs(n, i) for i in range(1, 6)]
            termos_str = ", ".join(str(t) for t in termos)

            print(f"Lei de formação: A_n = {expr_seq}")
            print(f"Primeiros 5 termos (n=1 a 5): [{termos_str}, ...]\n")
            continue

        # 4. ATALHO: MMC e MDC
        if entrada.startswith(("mmc", "mdc")):
            comando = entrada[:3]
            numeros = re.findall(r"\d+", entrada)
            if numeros:
                lista_num = [int(num) for num in numeros]
                res = sp.lcm(lista_num) if comando == "mmc" else sp.gcd(lista_num)
                print(f"Resultado ({comando.upper()}): {res}\n")
                continue
            else:
                print("Erro: Nenhum número informado para o comando!\n")
                continue

        # 5. ATALHO: Regra dos 180° (Ângulos)
        if "angulo" in entrada:
            valores = re.findall(r"\d+", entrada)
            if len(valores) == 2:
                res_angulo = 180 - (int(valores[0]) + int(valores[1]))
                if res_angulo <= 0:
                    print("Erro: A soma dos ângulos informados é maior ou igual a 180°!\n")
                else:
                    print(f"Resultado (Terceiro Ângulo): {res_angulo}°\n")
                continue

        # Processamento Geral:
        digitou_fracao = "|" in entrada
        entrada_formatada = entrada

        if "=" in entrada_formatada:
            partes_eq = entrada_formatada.split("=")
            if len(partes_eq) == 2:
                entrada_formatada = f"({partes_eq[0].strip()}) - ({partes_eq[1].strip()})"

        entrada_formatada = entrada_formatada.replace(".", "*")
        entrada_formatada = re.sub(r"(\d+),(\d+)", tratar_virgula, entrada_formatada)

        entrada_formatada = re.sub(r"(\d+)([a-z])", r"\1*\2", entrada_formatada)
        entrada_formatada = re.sub(r"(\d+)\(", r"\1*(", entrada_formatada)
        entrada_formatada = re.sub(r"\)([\(\w])", r")*\1", entrada_formatada)

        entrada_formatada = re.sub(r"(\d+)\!\!", r"factorial2(\1)", entrada_formatada)
        entrada_formatada = re.sub(r"(\d+)\!", r"factorial(\1)", entrada_formatada)

        entrada_formatada = re.sub(r"%\s*de\s*", "%*", entrada_formatada)
        entrada_formatada = re.sub(r"(\d+)%", r"(\1/100)", entrada_formatada)

        entrada_formatada = entrada_formatada.replace("|", "/")
        entrada_formatada = entrada_formatada.replace("÷", "/").replace(":", "/")
        entrada_formatada = entrada_formatada.replace("^", "**")

        entrada_formatada = entrada_formatada.replace("raiz de", "sqrt")
        entrada_formatada = entrada_formatada.replace("raiz", "sqrt")
        entrada_formatada = re.sub(r"sqrt\s*\((.*?)\)", r"sqrt(\1)", entrada_formatada)
        entrada_formatada = re.sub(r"sqrt\s*(\d+|\w+)", r"sqrt(\1)", entrada_formatada)
        entrada_formatada = re.sub(r"√\s*\((.*?)\)", r"sqrt(\1)", entrada_formatada)
        entrada_formatada = re.sub(r"√\s*(\d+|\w+)", r"sqrt(\1)", entrada_formatada)

        entrada_formatada = re.sub(r"sen\((.*?)\)", r"sin(rad(\1))", entrada_formatada)
        entrada_formatada = re.sub(r"cos\((.*?)\)", r"cos(rad(\1))", entrada_formatada)
        entrada_formatada = re.sub(r"tan\((.*?)\)", r"tan(rad(\1))", entrada_formatada)

        entrada_formatada = re.sub(r"(\d)\s*x\s*(\d)", r"\1*\2", entrada_formatada)

        funcoes_locais = {
            "sin": sp.sin,
            "cos": sp.cos,
            "tan": sp.tan,
            "sqrt": sp.sqrt,
            "factorial": sp.factorial,
            "factorial2": sp.factorial2,
            "rad": lambda g: g * sp.pi / 180,
            "sp": sp
        }

        expr = sp.sympify(entrada_formatada, locals=funcoes_locais)

        if expr.free_symbols:
            lista_vars = sorted(list(expr.free_symbols), key=lambda s: s.name)
            var_alvo = x if x in lista_vars else lista_vars[0]

            solucoes = sp.solve(expr, var_alvo)

            solucoes_formatadas = []
            for sol in solucoes:
                try:
                    num_val = float(sol.evalf())
                    decimal_str = str(int(num_val) if num_val.is_integer() else round(num_val, 4)).replace(".", ",")
                    solucoes_formatadas.append(f"{sol} (ou {decimal_str})")
                except (ValueError, TypeError):
                    solucoes_formatadas.append(str(sol))

            print(f"Solução para encontrar o valor de {var_alvo}: {solucoes_formatadas}\n")
        else:
            if digitou_fracao and isinstance(expr, (sp.Rational, sp.Integer)):
                fracao_estilo = str(expr).replace("/", "|")
                print(f"Resultado (Fração): {fracao_estilo}\n")
            else:
                res = expr.evalf()
                res_float = float(res)
                res_formatado = int(res_float) if res_float.is_integer() else round(res_float, 4)
                resposta_visual = str(res_formatado).replace(".", ",")
                print(f"Resultado: {resposta_visual}\n")

    except ZeroDivisionError:
        print("Erro: Divisão por zero!\n")
    except Exception as e:
        print("Expressão inválida. Tente novamente.\n")
